docs: replace npm with yarn
honojs/examples pull request #85
Opened 2023-04-19 16:18 UTC by xtyrrell

Thanks for your work on Hono!

In the `pages-stack` example, I noticed that `npm install` then `npm run dev` doesn't work. It throws the following error:

```
[proxy]: Internal Error: hono-examples@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at nF.getCandidates (/Users/max/.node/corepack/yarn/3.2.1/yarn.js:438:4480)
    at Bd.getCandidates (/Users/max/.node/corepack/yarn/3.2.1/yarn.js:396:1281)
    at /Users/max/.node/corepack/yarn/3.2.1/yarn.js:442:7764
    at Rg (/Users/max/.node/corepack/yarn/3.2.1/yarn.js:395:11098)
    at le (/Users/max/.node/corepack/yarn/3.2.1/yarn.js:442:7744)

✘ [ERROR] Proxy exited with status 1.
```

From the package.json, it looks like the package manager is suppose to be `yarn` not `npm`.

`npm run dev` works fine in `nextjs-stack`, but if the workspace config is to use `yarn`, then it should use `yarn` not `npm`.

2023-04-20 23:19 UTC, yusukebe requested changes

2023-04-20 23:19 UTC, yusukebe commented on nextjs-stack/README.md
> +yarn run dev
`yarn dev` is better.

2023-04-20 23:19 UTC, yusukebe commented on pages-stack/README.md
> +yarn run dev
`yarn dev` is better as same as above.

2023-04-20 23:20 UTC, yusukebe commented
HI @xtyrrell !

Thanks for creating the PR. You are right! We should use `yarn` instead of `npm`. 

I left some comments please check them.

2023-05-01 14:09 UTC, xtyrrell commented
Thanks for the suggestions, I've implemented them. :)

2023-05-01 14:32 UTC, yusukebe approved these changes

2023-05-01 14:32 UTC, merged